language: python

python:
    - "2.7"
    - "3.4"
    - "3.6"

env:
  - SH=bash
  - PACKAGE_VERSION="1.0.*"

matrix:
  allow_failures:
    - python: "2.7"

install:
    - pip install -r requirements.txt

script:
    - python -m unittest discover tests
